#:kivy 1.3.0

<CBL_DebugPanel>:
    BoxLayout:
    	orientation: 'vertical'
	    Label:
	        text: 'FPS: ' + root.fps if root.fps != None else 'Click to\nStart FPS'
	    Label:
	        text: 'Particles: ' + str(root.particles) if root.particles != None else 'None'

<ParticleWidget>:
    canvas:
        Color:
            rgb: (1,1,1)
        Rectangle:
            texture: self.texture
            size: self.size
            pos: self.pos